### PR TITLE
Set the status code in the Response

### PR DESCRIPTION
**Pull request by gerdadecio**
We want to access the status code of the response so that we can save it in our records as well. 

To access:
res = Response.new(response, params)
res.status
=> 200

And also, I modified the body and request_url methods a bit.

### CODE REVIEW

**Comment by drewnichols** [comment]
I had to update the unit test for Response to handle your last to PRs. Can you pull master and let me know if everything looks ok? If so I'll cut a minor release.

**Comment by gerdadecio** [comment]
@drewnichols will do it in a while. thanks!

**Comment by gerdadecio** [comment]
@drewnichols looks good. thanks for fixing the spec :)

**Comment by drewnichols** [comment]
@gerdadecio i published version 0.0.7 to rubygems.org if you'd like to begin pulling it from there

**Pull request merged**
